# Generated by Django 3.0.4 on 2020-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='user_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
