# Generated by Django 3.0.4 on 2020-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='secondary_id',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
