# Generated by Django 3.0.4 on 2020-04-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20200428_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='consumer',
        ),
        migrations.AddField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.Consumer'),
        ),
    ]
