# Generated by Django 3.0.5 on 2020-05-03 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_address_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_addr',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
