# Generated by Django 3.0.4 on 2020-04-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20200428_1808'),
        ('consumer', '0002_auto_20200428_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
