# Generated by Django 3.0.4 on 2020-03-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_address'),
        ('consumer', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Delivered'), ('S', 'Shipped'), ('P', 'Placed')], default='P', max_length=1)),
                ('total_price', models.IntegerField()),
                ('date_last_tracked', models.DateField()),
                ('date_delivered', models.DateField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.Consumer')),
                ('last_tracked_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courier.Courier')),
            ],
        ),
    ]
