# Generated by Django 3.0.4 on 2020-04-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20200428_1808'),
        ('consumer', '0003_auto_20200429_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Product'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
