# Generated by Django 3.0.5 on 2020-05-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryPersonnel', '0001_initial'),
        ('consumer', '0003_auto_20200503_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='last_tracked_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryPersonnel.DeliveryPersonnel'),
        ),
    ]
