# Generated by Django 3.0.5 on 2020-05-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_auto_20200503_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='date_last_tracked',
            new_name='last_tracked_on',
        ),
    ]
