# Generated by Django 3.0.4 on 2020-03-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20200319_2221'),
        ('consumer', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.Order')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
    ]
