# Generated by Django 3.0.5 on 2020-05-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryPersonnel', '0004_deliverypersonnel_user'),
        ('consumer', '0005_auto_20200504_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='last_tracked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryPersonnel.DeliveryPersonnel'),
        ),
    ]
