# Generated by Django 3.0.5 on 2020-05-04 12:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_auto_20200504_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='provider_addr',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='provider_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
