# Generated by Django 3.0.5 on 2020-05-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0010_auto_20200509_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.Consumer'),
        ),
    ]
