# Generated by Django 3.0.4 on 2020-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='profile_pic',
            field=models.ImageField(default='dps/profile.png', upload_to='dps/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='service_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
