# Generated by Django 3.0.4 on 2020-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_auto_20200428_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='profile_pic',
            field=models.ImageField(default='dps/courier.jpg', upload_to='dps/'),
        ),
    ]
