# Generated by Django 3.0.5 on 2020-05-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryPersonnel', '0001_initial'),
        ('courier', '0004_address_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryPersonnel.DeliveryPersonnel'),
        ),
    ]
