# Generated by Django 3.0.4 on 2020-03-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20200319_2221'),
        ('administrator', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Item'),
        ),
    ]
