# Generated by Django 3.0.4 on 2020-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_review_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
