# Generated by Django 3.0.5 on 2020-05-20 14:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(default='dps/profile.png', upload_to='dps/')),
                ('assigned', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('existing_location_addr', models.TextField(max_length=100, null=True)),
                ('existing_location_point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.Courier')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
