# Generated by Django 3.0.5 on 2020-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryPersonnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypersonnel',
            name='offday',
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
