# Generated by Django 3.0.5 on 2020-05-03 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveryPersonnel', '0003_auto_20200503_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonnel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
