# Generated by Django 3.0.4 on 2020-03-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='user_type',
        ),
    ]
