# Generated by Django 3.0.4 on 2020-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20200424_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_pic',
            field=models.ImageField(default='dps/profile.png', upload_to='dps/'),
        ),
    ]
