# Generated by Django 3.0.4 on 2020-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_provider_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='profile_pic',
            field=models.ImageField(default='dps/shop.jpg', upload_to='dps/'),
        ),
    ]
