# Generated by Django 3.0.4 on 2020-03-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rate',
            new_name='rating',
        ),
    ]
