# Generated by Django 3.0.5 on 2020-05-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_address_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
