# Generated by Django 3.0.5 on 2020-05-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
